trigger: none

pr:
- master

pool:
  vmImage: 'Ubuntu-18.04'

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
- template: ../steps/setup
- template: templates/yml/python/steps/run-invoke.yml@templates
  parameters:
    tasksAndArguments: 'lint'
    taskDisplayName: 'Lint'
