trigger:
- master

pr:
- master

pool:
  vmImage: 'macos-10.14'

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
  - template: ../steps/setup.yml
  - template: ../steps/run-unit-tests.yml
    parameters:
      envName: 'Mac'
