trigger: none

pr:
- master

pool:
  vmImage: 'Ubuntu-18.04'

resources:
  repositories:
  - repository: templates
    type: github
    name: swellaby/azure-pipelines-templates
    endpoint: swellaby

steps:
- template: ../steps/setup.yml
- template: ../steps/run-unit-tests.yml
  parameters:
    envName: 'Sonar'

- bash: |
   export PACKAGE_VERSION=$(invoke print-version)
    echo "##vso[task.setvariable variable=packageVersion]$PACKAGE_VERSION"
  displayName: 'Get package version'

- template: templates/yml/any/sonar/run-sonar-cloud-cli-analysis.yml@templates
  parameters:
    projectVersion: $(packageVersion)
