version: 1

update_configs:
  - package_manager: "python"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "calebcartwright"
    default_assignees:
      - "calebcartwright"
    default_labels:
      - "dependencies"
